apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy-esiee-node-app
  name: dummy-esiee-node-app
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: dummy-esiee-node-app
  type: LoadBalancer
